// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'58836baebf67b3a809ff6ebf2ab25f8520eb47a78020ed8bccba5c3509b188c4'>;
export type ExecutionHash =
  ExecutionHashBase<'9210450d43702c532dee1184722971d04cee7c75dab5e6da887165f2ed1e9b96'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Acompanante: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly reservaId: CodecTypes['pg/text@1']['output'];
      readonly personaId: CodecTypes['pg/text@1']['output'];
      readonly tipoHuesped: 'ADULTO' | 'NINO' | 'BEBE';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Alojamiento: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly tipo: 'HABITACION' | 'CABANA';
      readonly capacidad: CodecTypes['pg/int4@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
      readonly estado: 'OPERATIVO' | 'MANTENIMIENTO' | 'FUERA_SERVICIO';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Persona: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly tipoDocumento: 'CC' | 'CE' | 'TI' | 'PASAPORTE';
      readonly documento: CodecTypes['pg/text@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly fechaNacimiento: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly contacto: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'] | null;
      readonly eps: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Plan: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
      readonly precio: CodecTypes['pg/float8@1']['output'];
      readonly soloParejas: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly PlanServicio: {
      readonly planId: CodecTypes['pg/text@1']['output'];
      readonly servicioId: CodecTypes['pg/text@1']['output'];
    };
    readonly Reserva: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly titularId: CodecTypes['pg/text@1']['output'];
      readonly planId: CodecTypes['pg/text@1']['output'];
      readonly precioPlan: CodecTypes['pg/float8@1']['output'];
      readonly alojamientoId: CodecTypes['pg/text@1']['output'] | null;
      readonly fechaIngreso: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly fechaSalida: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly estado: 'PENDIENTE_PAGO' | 'CONFIRMADA' | 'CANCELADA';
      readonly total: CodecTypes['pg/float8@1']['output'];
      readonly observaciones: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly ReservaServicio: {
      readonly reservaId: CodecTypes['pg/text@1']['output'];
      readonly servicioId: CodecTypes['pg/text@1']['output'];
      readonly cantidad: CodecTypes['pg/int4@1']['output'];
      readonly precio: CodecTypes['pg/float8@1']['output'];
    };
    readonly Servicio: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
      readonly precio: CodecTypes['pg/float8@1']['output'];
      readonly soloRomantico: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Acompanante: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly reservaId: CodecTypes['pg/text@1']['input'];
      readonly personaId: CodecTypes['pg/text@1']['input'];
      readonly tipoHuesped: 'ADULTO' | 'NINO' | 'BEBE';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Alojamiento: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly tipo: 'HABITACION' | 'CABANA';
      readonly capacidad: CodecTypes['pg/int4@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
      readonly estado: 'OPERATIVO' | 'MANTENIMIENTO' | 'FUERA_SERVICIO';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Persona: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly tipoDocumento: 'CC' | 'CE' | 'TI' | 'PASAPORTE';
      readonly documento: CodecTypes['pg/text@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly fechaNacimiento: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly contacto: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'] | null;
      readonly eps: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Plan: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
      readonly precio: CodecTypes['pg/float8@1']['input'];
      readonly soloParejas: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly PlanServicio: {
      readonly planId: CodecTypes['pg/text@1']['input'];
      readonly servicioId: CodecTypes['pg/text@1']['input'];
    };
    readonly Reserva: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly titularId: CodecTypes['pg/text@1']['input'];
      readonly planId: CodecTypes['pg/text@1']['input'];
      readonly precioPlan: CodecTypes['pg/float8@1']['input'];
      readonly alojamientoId: CodecTypes['pg/text@1']['input'] | null;
      readonly fechaIngreso: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly fechaSalida: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly estado: 'PENDIENTE_PAGO' | 'CONFIRMADA' | 'CANCELADA';
      readonly total: CodecTypes['pg/float8@1']['input'];
      readonly observaciones: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly ReservaServicio: {
      readonly reservaId: CodecTypes['pg/text@1']['input'];
      readonly servicioId: CodecTypes['pg/text@1']['input'];
      readonly cantidad: CodecTypes['pg/int4@1']['input'];
      readonly precio: CodecTypes['pg/float8@1']['input'];
    };
    readonly Servicio: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
      readonly precio: CodecTypes['pg/float8@1']['input'];
      readonly soloRomantico: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly acompanante: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly personaId: CodecTypes['pg/text@1']['output'];
      readonly reservaId: CodecTypes['pg/text@1']['output'];
      readonly tipoHuesped: 'ADULTO' | 'NINO' | 'BEBE';
    };
    readonly alojamiento: {
      readonly capacidad: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
      readonly estado: 'OPERATIVO' | 'MANTENIMIENTO' | 'FUERA_SERVICIO';
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly tipo: 'HABITACION' | 'CABANA';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly persona: {
      readonly contacto: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly documento: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'] | null;
      readonly eps: CodecTypes['pg/text@1']['output'] | null;
      readonly fechaNacimiento: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly tipoDocumento: 'CC' | 'CE' | 'TI' | 'PASAPORTE';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly plan: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly precio: CodecTypes['pg/float8@1']['output'];
      readonly soloParejas: CodecTypes['pg/bool@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly planServicio: {
      readonly planId: CodecTypes['pg/text@1']['output'];
      readonly servicioId: CodecTypes['pg/text@1']['output'];
    };
    readonly reserva: {
      readonly alojamientoId: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly estado: 'PENDIENTE_PAGO' | 'CONFIRMADA' | 'CANCELADA';
      readonly fechaIngreso: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly fechaSalida: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly observaciones: CodecTypes['pg/text@1']['output'] | null;
      readonly planId: CodecTypes['pg/text@1']['output'];
      readonly precioPlan: CodecTypes['pg/float8@1']['output'];
      readonly titularId: CodecTypes['pg/text@1']['output'];
      readonly total: CodecTypes['pg/float8@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly reservaServicio: {
      readonly cantidad: CodecTypes['pg/int4@1']['output'];
      readonly precio: CodecTypes['pg/float8@1']['output'];
      readonly reservaId: CodecTypes['pg/text@1']['output'];
      readonly servicioId: CodecTypes['pg/text@1']['output'];
    };
    readonly servicio: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly precio: CodecTypes['pg/float8@1']['output'];
      readonly soloRomantico: CodecTypes['pg/bool@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly acompanante: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly personaId: CodecTypes['pg/text@1']['input'];
      readonly reservaId: CodecTypes['pg/text@1']['input'];
      readonly tipoHuesped: 'ADULTO' | 'NINO' | 'BEBE';
    };
    readonly alojamiento: {
      readonly capacidad: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
      readonly estado: 'OPERATIVO' | 'MANTENIMIENTO' | 'FUERA_SERVICIO';
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly tipo: 'HABITACION' | 'CABANA';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly persona: {
      readonly contacto: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly documento: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'] | null;
      readonly eps: CodecTypes['pg/text@1']['input'] | null;
      readonly fechaNacimiento: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly tipoDocumento: 'CC' | 'CE' | 'TI' | 'PASAPORTE';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly plan: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly precio: CodecTypes['pg/float8@1']['input'];
      readonly soloParejas: CodecTypes['pg/bool@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly planServicio: {
      readonly planId: CodecTypes['pg/text@1']['input'];
      readonly servicioId: CodecTypes['pg/text@1']['input'];
    };
    readonly reserva: {
      readonly alojamientoId: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly estado: 'PENDIENTE_PAGO' | 'CONFIRMADA' | 'CANCELADA';
      readonly fechaIngreso: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly fechaSalida: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly observaciones: CodecTypes['pg/text@1']['input'] | null;
      readonly planId: CodecTypes['pg/text@1']['input'];
      readonly precioPlan: CodecTypes['pg/float8@1']['input'];
      readonly titularId: CodecTypes['pg/text@1']['input'];
      readonly total: CodecTypes['pg/float8@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly reservaServicio: {
      readonly cantidad: CodecTypes['pg/int4@1']['input'];
      readonly precio: CodecTypes['pg/float8@1']['input'];
      readonly reservaId: CodecTypes['pg/text@1']['input'];
      readonly servicioId: CodecTypes['pg/text@1']['input'];
    };
    readonly servicio: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly precio: CodecTypes['pg/float8@1']['input'];
      readonly soloRomantico: CodecTypes['pg/bool@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Servicio = {
    id: CodecTypes['pg/text@1']['output'];
    nombre: CodecTypes['pg/text@1']['output'];
    descripcion: CodecTypes['pg/text@1']['output'] | null;
    precio: CodecTypes['pg/float8@1']['output'];
    soloRomantico: CodecTypes['pg/bool@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    planes: public_PlanServicio[];
    reservas: public_ReservaServicio[];
    readonly [RelationKeys]?: 'planes' | 'reservas';
  };
  export type public_Plan = {
    id: CodecTypes['pg/text@1']['output'];
    nombre: CodecTypes['pg/text@1']['output'];
    descripcion: CodecTypes['pg/text@1']['output'] | null;
    precio: CodecTypes['pg/float8@1']['output'];
    soloParejas: CodecTypes['pg/bool@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    reservas: public_Reserva[];
    servicios: public_PlanServicio[];
    readonly [RelationKeys]?: 'reservas' | 'servicios';
  };
  export type public_Alojamiento = {
    id: CodecTypes['pg/text@1']['output'];
    nombre: CodecTypes['pg/text@1']['output'];
    tipo: 'HABITACION' | 'CABANA';
    capacidad: CodecTypes['pg/int4@1']['output'];
    descripcion: CodecTypes['pg/text@1']['output'] | null;
    estado: 'OPERATIVO' | 'MANTENIMIENTO' | 'FUERA_SERVICIO';
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    reservas: public_Reserva[];
    readonly [RelationKeys]?: 'reservas';
  };
  export type public_Persona = {
    id: CodecTypes['pg/text@1']['output'];
    tipoDocumento: 'CC' | 'CE' | 'TI' | 'PASAPORTE';
    documento: CodecTypes['pg/text@1']['output'];
    nombre: CodecTypes['pg/text@1']['output'];
    fechaNacimiento: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    contacto: CodecTypes['pg/text@1']['output'];
    email: CodecTypes['pg/text@1']['output'] | null;
    eps: CodecTypes['pg/text@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    acompanantes: public_Acompanante[];
    reservas: public_Reserva[];
    readonly [RelationKeys]?: 'acompanantes' | 'reservas';
  };
  export type public_Reserva = {
    id: CodecTypes['pg/text@1']['output'];
    titularId: CodecTypes['pg/text@1']['output'];
    planId: CodecTypes['pg/text@1']['output'];
    precioPlan: CodecTypes['pg/float8@1']['output'];
    alojamientoId: CodecTypes['pg/text@1']['output'] | null;
    fechaIngreso: CodecTypes['pg/timestamptz-temporal@1']['output'];
    fechaSalida: CodecTypes['pg/timestamptz-temporal@1']['output'];
    estado: 'PENDIENTE_PAGO' | 'CONFIRMADA' | 'CANCELADA';
    total: CodecTypes['pg/float8@1']['output'];
    observaciones: CodecTypes['pg/text@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    acompanantes: public_Acompanante[];
    alojamiento: public_Alojamiento | null;
    plan: public_Plan;
    servicios: public_ReservaServicio[];
    titular: public_Persona;
    readonly [RelationKeys]?: 'acompanantes' | 'alojamiento' | 'plan' | 'servicios' | 'titular';
  };
  export type public_Acompanante = {
    id: CodecTypes['pg/text@1']['output'];
    reservaId: CodecTypes['pg/text@1']['output'];
    personaId: CodecTypes['pg/text@1']['output'];
    tipoHuesped: 'ADULTO' | 'NINO' | 'BEBE';
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    persona: public_Persona;
    reserva: public_Reserva;
    readonly [RelationKeys]?: 'persona' | 'reserva';
  };
  export type public_PlanServicio = {
    planId: CodecTypes['pg/text@1']['output'];
    servicioId: CodecTypes['pg/text@1']['output'];
    plan: public_Plan;
    servicio: public_Servicio;
    readonly [RelationKeys]?: 'plan' | 'servicio';
  };
  export type public_ReservaServicio = {
    reservaId: CodecTypes['pg/text@1']['output'];
    servicioId: CodecTypes['pg/text@1']['output'];
    cantidad: CodecTypes['pg/int4@1']['output'];
    precio: CodecTypes['pg/float8@1']['output'];
    reserva: public_Reserva;
    servicio: public_Servicio;
    readonly [RelationKeys]?: 'reserva' | 'servicio';
  };
}

export declare const models: {
  public: {
    Servicio: Models.public_Servicio;
    Plan: Models.public_Plan;
    Alojamiento: Models.public_Alojamiento;
    Persona: Models.public_Persona;
    Reserva: Models.public_Reserva;
    Acompanante: Models.public_Acompanante;
    PlanServicio: Models.public_PlanServicio;
    ReservaServicio: Models.public_ReservaServicio;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly acompanante: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly reservaId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly personaId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly tipoHuesped: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['reservaId', 'personaId'] }];
              indexes: readonly [
                {
                  readonly name: 'acompanante_reservaId_idx_178ec2fd';
                  readonly prefix: 'acompanante_reservaId_idx';
                  readonly columns: readonly ['reservaId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'acompanante_personaId_idx_758ca1fb';
                  readonly prefix: 'acompanante_personaId_idx';
                  readonly columns: readonly ['personaId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'acompanante';
                    readonly columns: readonly ['reservaId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'reserva';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'acompanante';
                    readonly columns: readonly ['personaId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'persona';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly alojamiento: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly tipo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly capacidad: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly descripcion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly estado: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'OPERATIVO'>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly persona: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly tipoDocumento: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly documento: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly fechaNacimiento: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly contacto: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly eps: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['documento'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly plan: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly descripcion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly precio: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly soloParejas: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['nombre'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly planServicio: {
              columns: {
                readonly planId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly servicioId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['planId', 'servicioId'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'planServicio_planId_idx_5b32079a';
                  readonly prefix: 'planServicio_planId_idx';
                  readonly columns: readonly ['planId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'planServicio_servicioId_idx_70be2758';
                  readonly prefix: 'planServicio_servicioId_idx';
                  readonly columns: readonly ['servicioId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'planServicio';
                    readonly columns: readonly ['planId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'plan';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'planServicio';
                    readonly columns: readonly ['servicioId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'servicio';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly reserva: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly titularId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly planId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly precioPlan: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly alojamientoId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly fechaIngreso: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly fechaSalida: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly estado: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDIENTE_PAGO'>;
                  };
                };
                readonly total: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly observaciones: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'reserva_titularId_idx_8aeff669';
                  readonly prefix: 'reserva_titularId_idx';
                  readonly columns: readonly ['titularId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'reserva_planId_idx_5b32079a';
                  readonly prefix: 'reserva_planId_idx';
                  readonly columns: readonly ['planId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'reserva_alojamientoId_idx_662b074b';
                  readonly prefix: 'reserva_alojamientoId_idx';
                  readonly columns: readonly ['alojamientoId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'reserva';
                    readonly columns: readonly ['titularId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'persona';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'reserva';
                    readonly columns: readonly ['planId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'plan';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'reserva';
                    readonly columns: readonly ['alojamientoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'alojamiento';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly reservaServicio: {
              columns: {
                readonly reservaId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly servicioId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly cantidad: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                  };
                };
                readonly precio: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['reservaId', 'servicioId'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'reservaServicio_reservaId_idx_178ec2fd';
                  readonly prefix: 'reservaServicio_reservaId_idx';
                  readonly columns: readonly ['reservaId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'reservaServicio_servicioId_idx_70be2758';
                  readonly prefix: 'reservaServicio_servicioId_idx';
                  readonly columns: readonly ['servicioId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'reservaServicio';
                    readonly columns: readonly ['reservaId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'reserva';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'reservaServicio';
                    readonly columns: readonly ['servicioId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'servicio';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly servicio: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly descripcion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly precio: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly soloRomantico: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['nombre'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly EstadoAlojamiento: {
              readonly kind: 'valueSet';
              readonly values: readonly ['OPERATIVO', 'MANTENIMIENTO', 'FUERA_SERVICIO'];
            };
            readonly EstadoReserva: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PENDIENTE_PAGO', 'CONFIRMADA', 'CANCELADA'];
            };
            readonly TipoAlojamiento: {
              readonly kind: 'valueSet';
              readonly values: readonly ['HABITACION', 'CABANA'];
            };
            readonly TipoDocumento: {
              readonly kind: 'valueSet';
              readonly values: readonly ['CC', 'CE', 'TI', 'PASAPORTE'];
            };
            readonly TipoHuesped: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ADULTO', 'NINO', 'BEBE'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly servicio: { readonly namespace: 'public' & NamespaceId; readonly model: 'Servicio' };
    readonly plan: { readonly namespace: 'public' & NamespaceId; readonly model: 'Plan' };
    readonly alojamiento: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Alojamiento';
    };
    readonly persona: { readonly namespace: 'public' & NamespaceId; readonly model: 'Persona' };
    readonly reserva: { readonly namespace: 'public' & NamespaceId; readonly model: 'Reserva' };
    readonly acompanante: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Acompanante';
    };
    readonly planServicio: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'PlanServicio';
    };
    readonly reservaServicio: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ReservaServicio';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Acompanante: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly reservaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly personaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tipoHuesped: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly persona: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Persona';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['personaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly reserva: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Reserva';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['reservaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'acompanante';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly reservaId: { readonly column: 'reservaId' };
                readonly personaId: { readonly column: 'personaId' };
                readonly tipoHuesped: { readonly column: 'tipoHuesped' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Alojamiento: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tipo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly capacidad: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly descripcion: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly estado: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly reservas: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Reserva';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['alojamientoId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'alojamiento';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nombre: { readonly column: 'nombre' };
                readonly tipo: { readonly column: 'tipo' };
                readonly capacidad: { readonly column: 'capacidad' };
                readonly descripcion: { readonly column: 'descripcion' };
                readonly estado: { readonly column: 'estado' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Persona: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tipoDocumento: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly documento: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fechaNacimiento: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly contacto: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly eps: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly acompanantes: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Acompanante';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['personaId'];
                };
              };
              readonly reservas: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Reserva';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['titularId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'persona';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly tipoDocumento: { readonly column: 'tipoDocumento' };
                readonly documento: { readonly column: 'documento' };
                readonly nombre: { readonly column: 'nombre' };
                readonly fechaNacimiento: { readonly column: 'fechaNacimiento' };
                readonly contacto: { readonly column: 'contacto' };
                readonly email: { readonly column: 'email' };
                readonly eps: { readonly column: 'eps' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Plan: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly descripcion: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly precio: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly soloParejas: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly reservas: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Reserva';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['planId'];
                };
              };
              readonly servicios: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'PlanServicio';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['planId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'plan';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nombre: { readonly column: 'nombre' };
                readonly descripcion: { readonly column: 'descripcion' };
                readonly precio: { readonly column: 'precio' };
                readonly soloParejas: { readonly column: 'soloParejas' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly PlanServicio: {
            readonly fields: {
              readonly planId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly servicioId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly plan: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Plan' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['planId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly servicio: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Servicio';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['servicioId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'planServicio';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly planId: { readonly column: 'planId' };
                readonly servicioId: { readonly column: 'servicioId' };
              };
            };
          };
          readonly Reserva: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly titularId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly planId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly precioPlan: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly alojamientoId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fechaIngreso: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly fechaSalida: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly estado: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly total: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly observaciones: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly acompanantes: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Acompanante';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['reservaId'];
                };
              };
              readonly alojamiento: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Alojamiento';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['alojamientoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly plan: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Plan' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['planId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly servicios: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ReservaServicio';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['reservaId'];
                };
              };
              readonly titular: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Persona';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['titularId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'reserva';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly titularId: { readonly column: 'titularId' };
                readonly planId: { readonly column: 'planId' };
                readonly precioPlan: { readonly column: 'precioPlan' };
                readonly alojamientoId: { readonly column: 'alojamientoId' };
                readonly fechaIngreso: { readonly column: 'fechaIngreso' };
                readonly fechaSalida: { readonly column: 'fechaSalida' };
                readonly estado: { readonly column: 'estado' };
                readonly total: { readonly column: 'total' };
                readonly observaciones: { readonly column: 'observaciones' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly ReservaServicio: {
            readonly fields: {
              readonly reservaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly servicioId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly cantidad: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly precio: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
            };
            readonly relations: {
              readonly reserva: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Reserva';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['reservaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly servicio: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Servicio';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['servicioId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'reservaServicio';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly reservaId: { readonly column: 'reservaId' };
                readonly servicioId: { readonly column: 'servicioId' };
                readonly cantidad: { readonly column: 'cantidad' };
                readonly precio: { readonly column: 'precio' };
              };
            };
          };
          readonly Servicio: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly descripcion: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly precio: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly soloRomantico: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly planes: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'PlanServicio';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['servicioId'];
                };
              };
              readonly reservas: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ReservaServicio';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['servicioId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'servicio';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nombre: { readonly column: 'nombre' };
                readonly descripcion: { readonly column: 'descripcion' };
                readonly precio: { readonly column: 'precio' };
                readonly soloRomantico: { readonly column: 'soloRomantico' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly TipoDocumento: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'CC'; readonly value: 'CC' },
              { readonly name: 'CE'; readonly value: 'CE' },
              { readonly name: 'TI'; readonly value: 'TI' },
              { readonly name: 'PASAPORTE'; readonly value: 'PASAPORTE' },
            ];
          };
          readonly TipoHuesped: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ADULTO'; readonly value: 'ADULTO' },
              { readonly name: 'NINO'; readonly value: 'NINO' },
              { readonly name: 'BEBE'; readonly value: 'BEBE' },
            ];
          };
          readonly EstadoReserva: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDIENTE_PAGO'; readonly value: 'PENDIENTE_PAGO' },
              { readonly name: 'CONFIRMADA'; readonly value: 'CONFIRMADA' },
              { readonly name: 'CANCELADA'; readonly value: 'CANCELADA' },
            ];
          };
          readonly TipoAlojamiento: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'HABITACION'; readonly value: 'HABITACION' },
              { readonly name: 'CABANA'; readonly value: 'CABANA' },
            ];
          };
          readonly EstadoAlojamiento: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'OPERATIVO'; readonly value: 'OPERATIVO' },
              { readonly name: 'MANTENIMIENTO'; readonly value: 'MANTENIMIENTO' },
              { readonly name: 'FUERA_SERVICIO'; readonly value: 'FUERA_SERVICIO' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'acompanante';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'alojamiento';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'alojamiento';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'persona';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'persona';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'plan';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'plan';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'reserva';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'reserva';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'servicio';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'servicio';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
